import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import Head from 'next/head'
import PageHeader from './components/page-header'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl">
      <Head>
        <meta charSet="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      </Head>
      <body className='container-fluid'>
        <div className='row'>
          <PageHeader></PageHeader>
        </div>
        <main className='row mt-5'>{children}</main>
      </body>
    </html>
  )
}
